#!/bin/bash
set -e

# ESP-IDF setup (must run in same shell as build)
IDF_DIR="/Volumes/DOCKCASE/m5stack/esp-idf"
export IDF_PYTHON_ENV_PATH="$HOME/.espressif/python_env/idf5.5_py3.9_env"
. "$IDF_DIR/export.sh" > /dev/null 2>&1

REPO="/Volumes/DOCKCASE/research/matrixled"
WORK="/Volumes/DOCKCASE/research/matrixled/build_firmware"
MP="$WORK/micropython"

echo "=== 1. Clone MicroPython (v1.27.0) ==="
if [ ! -d "$MP" ]; then
  git clone --depth 1 --branch v1.27.0 https://github.com/micropython/micropython "$MP"
fi
cd "$MP"
git submodule update --init lib/micropython-lib 2>/dev/null || true

echo "=== 2. Build mpy-cross ==="
make -C mpy-cross -j"$(nproc)" 2>&1 | tail -3

echo "=== 3. Generate embedded_assets.py ==="
python3 - <<'PY'
css = open('/Volumes/DOCKCASE/research/matrixled/led_matrix_project/static/style.css').read()
with open('/Volumes/DOCKCASE/research/matrixled/led_matrix_project/embedded_assets.py', 'w') as f:
    f.write('# Auto-generated by build. Do not edit.\nCSS = ' + repr(css) + '\n')
print('embedded_assets.py written (%d bytes CSS)' % len(css))
PY

echo "=== 4. Build ESP32-C6 firmware ==="
cd "$MP/ports/esp32"
make BOARD=ESP32_GENERIC_C6 submodules 2>&1 | tail -2
make BOARD=ESP32_GENERIC_C6 \
     FROZEN_MANIFEST="$REPO/manifest.py" \
     USER_C_MODULES="$REPO/usermodules/micropython.cmake" \
     -j"$(nproc)" 2>&1 | tail -30

echo "=== 5. Copy firmware.bin ==="
cp -v "$MP/ports/esp32/build-ESP32_GENERIC_C6/firmware.bin" "$REPO/firmware.bin"
echo "=== DONE ==="
ls -la "$REPO/firmware.bin"
